name: §6KitsPVP§c
main: Yoyu\KitsPVP\Main
version: §c1.0alpha§a
api: 4.0.0
author: HuaYoyu
load: "STARTUP"
description: "KitsPvP is same like pc plugins..."
website: "https://github.com/Yoyu666/KitPVP"
commands:
    kit:
        description: Kit Command
        use: "/kit"
        permission: kit.command
    kits:
        description: Show all kits Commands
        use: "/kits"
        permission: kits.command

permissions:
    kit.command:
        description: "Kit Command"
        default: true
    kits.command:
        description: "Kits Command"
        default: true
    kit.free.command:
        description: "Free"
        default: true
    kit.archer.command:
        description: "Archer"
        default: true
    kit.tank.command:
        description: "Tank"
        default: op
    kit.knight.command:
        description: "Knight"
        default: op
    kit.warrior.command:
        description: "Warrior"
        default: true
    kit.miner.command:
        description: "Miner"
        default: op
    kit.admin.command:
        description: "Admin"
        default: op
